import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — SpiderShield",
  description: "SpiderShield terms of service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-32 pb-24">
      <div className="mx-auto max-w-3xl px-6">
        <div className="mb-4">
          <Link href="/" className="text-sm text-muted hover:text-spider-red transition-colors">
            &larr; Home
          </Link>
        </div>

        <h1 className="mb-4 text-4xl font-bold text-white">Terms of Service</h1>
        <p className="mb-12 text-base text-muted">Last updated: March 10, 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="mb-3 text-xl font-bold text-white">1. Open-Source Software</h2>
            <p className="text-base text-body leading-relaxed">
              The SpiderShield SDK, CLI, and runtime guard are open-source software licensed under the MIT License. You may use, modify, and distribute the software in accordance with the MIT License terms. The full license text is available in the{" "}
              <a
                href="https://github.com/teehooai/spidershield/blob/master/LICENSE"
                target="_blank"
                rel="noopener noreferrer"
                className="text-spider-red hover:text-spider-red-hover transition-colors"
              >
                GitHub repository
              </a>.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">2. SpiderShield Cloud</h2>
            <p className="text-base text-body leading-relaxed">
              SpiderShield Cloud is a separate commercial service. By creating a Cloud account, you agree to these additional terms. Cloud service availability is provided on a best-effort basis for free tiers, and with SLA guarantees for Enterprise tiers.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">3. SpiderRating</h2>
            <p className="text-base text-body leading-relaxed">
              SpiderRating security scores are generated by automated static analysis and represent a best-effort assessment. Scores do not constitute a security certification or guarantee. A high score means fewer detected issues, not the absence of vulnerabilities.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">4. No Warranty</h2>
            <p className="text-base text-body leading-relaxed">
              THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND. SpiderShield is a security tool that helps detect known patterns, but cannot guarantee the absence of vulnerabilities. You are responsible for your own security posture.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">5. Limitation of Liability</h2>
            <p className="text-base text-body leading-relaxed">
              IN NO EVENT SHALL TEEHOOAI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO YOUR USE OF SPIDERSHIELD, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">6. Acceptable Use</h2>
            <p className="text-base text-body leading-relaxed">
              You agree not to use SpiderShield Cloud to: (a) violate any applicable law, (b) transmit malware or malicious content, (c) attempt to gain unauthorized access to our systems, (d) interfere with the service for other users.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">7. Changes to Terms</h2>
            <p className="text-base text-body leading-relaxed">
              We may update these terms from time to time. Material changes will be communicated via email (for Cloud users) or via the GitHub repository. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-bold text-white">8. Contact</h2>
            <p className="text-base text-body leading-relaxed">
              For questions about these terms, email{" "}
              <a href="mailto:legal@spidershield.dev" className="text-spider-red hover:text-spider-red-hover transition-colors">
                legal@spidershield.dev
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
